import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it, vi } from 'vitest'
import { FormStateContext } from '../../context/formContextState'
import Step5Employment from '.'

const renderStep = (formData = {}) => { const updateFormData = vi.fn(); const onBack = vi.fn(); const onContinue = vi.fn(); render(<FormStateContext.Provider value={{ formData, updateFormData }}><Step5Employment onBack={onBack} onContinue={onContinue} /></FormStateContext.Provider>); return { updateFormData, onBack, onContinue } }

describe('Step 5 Employment', () => {
  it('renders and requires Employment Type only after submit', async () => { const user = userEvent.setup(); renderStep(); expect(screen.getByRole('group', { name: /Employment Type/ })).toBeInTheDocument(); expect(screen.queryByText('Employment Type is required')).not.toBeInTheDocument(); await user.click(screen.getByRole('button', { name: /Continue/ })); expect(await screen.findByText('Employment Type is required')).toBeInTheDocument() })
  it('renders only the selected employment branch', async () => { const user = userEvent.setup(); renderStep(); await user.click(screen.getByRole('radio', { name: 'Salaried' })); expect(screen.getByLabelText(/Company Name/)).toBeInTheDocument(); expect(screen.queryByLabelText(/GST Number/)).not.toBeInTheDocument(); await user.click(screen.getByRole('radio', { name: 'Self-Employed' })); expect(screen.getByLabelText(/Monthly Income/)).toBeInTheDocument(); expect(screen.queryByLabelText(/Company Name/)).not.toBeInTheDocument(); await user.click(screen.getByRole('radio', { name: 'Business Owner' })); expect(screen.getByLabelText(/GST Number/)).toBeInTheDocument(); expect(screen.queryByLabelText(/Monthly Income/)).not.toBeInTheDocument() })
  it('disables Salaried for a Business Loan', () => { renderStep({ loanType: 'business' }); expect(screen.getByRole('radio', { name: 'Salaried' })).toBeDisabled() })
  it('continues with normalized valid salaried data', async () => { const user = userEvent.setup(); const result = renderStep(); await user.click(screen.getByRole('radio', { name: 'Salaried' })); await user.type(screen.getByLabelText(/Company Name/), 'Acme Ltd'); await user.type(screen.getByLabelText(/Designation/), 'Engineer'); await user.type(screen.getByLabelText(/Monthly Net Salary/), '50000'); await user.type(screen.getByLabelText(/Years of Experience/), '4'); await user.click(screen.getByRole('button', { name: /Continue/ })); expect(result.onContinue).toHaveBeenCalled(); expect(result.updateFormData).toHaveBeenCalledWith({ employmentDetails: expect.objectContaining({ monthlyNetSalary: 50000, affordabilityMonthlyIncome: 50000 }) }) })
  it('preserves current values on Back', async () => { const user = userEvent.setup(); const result = renderStep(); await user.click(screen.getByRole('radio', { name: 'Salaried' })); await user.type(screen.getByLabelText(/Company Name/), 'Acme Ltd'); await user.click(screen.getByRole('button', { name: /Back/ })); expect(result.onBack).toHaveBeenCalled(); expect(result.updateFormData).toHaveBeenCalledWith({ employmentDetails: expect.objectContaining({ companyName: 'Acme Ltd' }) }) })
})
