import { beforeEach, describe, expect, it } from 'vitest'
import { createSubmittedApplication, generateApplicationId, persistSubmittedApplication, readSubmittedApplication, simulateSubmission, validateApplication } from './applicationSubmission'

const valid = { loanType: 'personal', loanAmount: '100000', loanTenure: '12', loanPurpose: 'medical', referralCode: '', fullName: 'Asha Rao', dateOfBirth: '1990-01-01', gender: 'female', maritalStatus: 'single', fatherName: 'Ravi Rao', motherName: 'Maya Rao', email: 'asha@example.com', mobileNumber: '9876543210', alternateMobileNumber: '', panNumber: 'ABCPD1234E', aadhaarNumber: '999999990019', aadhaarConsent: true, panVerified: true, aadhaarVerified: true, addressDetails: { currentAddressLine1: '12 Main Road', currentAddressLine2: '', currentLandmark: '', currentPinCode: '560001', currentCity: 'Bengaluru', currentState: 'Karnataka', currentPostOffice: '', residenceType: 'Owned', monthlyRent: '', yearsAtCurrentAddress: 2, permanentAddressLine1: '12 Main Road', permanentAddressLine2: '', permanentLandmark: '', permanentPinCode: '560001', permanentCity: 'Bengaluru', permanentState: 'Karnataka', permanentPostOffice: '', sameAsCurrent: true, previousAddressLine1: '', previousPinCode: '', previousCity: '', previousState: '', currentLookupState: '', permanentLookupState: '' }, employmentDetails: { employmentType: 'salaried', companyName: 'Acme Ltd', designation: 'Engineer', monthlyNetSalary: 50000, yearsOfExperience: 4 }, documents: { identityProof: [{ name: 'id.pdf' }], addressProof: [{ name: 'address.pdf' }], bankStatement: [{ name: 'bank.pdf' }], salarySlips: [{ name: 'salary.pdf' }] }, eSignature: 'data:image/png;base64,abc' }

describe('application submission utilities', () => {
  beforeEach(() => localStorage.clear())
  it('generates the required unique ID format', () => { expect(generateApplicationId(new Date('2026-01-01'))).toMatch(/^LOAN-2026-[A-Z0-9]{6}$/) })
  it('validates required data and verification', () => { expect(validateApplication(valid)).toEqual([]); expect(validateApplication({})).not.toEqual([]) })
  it('masks sensitive identifiers and persists submitted data', () => { const result = createSubmittedApplication(valid, new Date('2026-08-15')); persistSubmittedApplication(result); expect(readSubmittedApplication()).toEqual(result); expect(result.applicationData.panNumber).toBe('******234E'); expect(result.applicationData.aadhaarNumber).toBe('********0019') })
  it('supports a simulated failure followed by retry without creating an ID', async () => { await expect(simulateSubmission({ shouldFail: true, delay: 0 })).rejects.toThrow(/could not submit/i); expect(localStorage.length).toBe(0); await expect(simulateSubmission({ delay: 0 })).resolves.toBeUndefined() })
})
